version: '3.7'

services:
  docker:
    image: docker:20.10.16-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_DRIVER: overlay
#    command: ["--storage-driver=overlay2"]
    volumes:
      - docker_lib:/var/lib/docker
      - cache:/cache
      - builds:/builds
    networks:
      gitlab-runner:

  runner:
    image: gitlab/gitlab-runner:alpine3.15-v15.5.0
    environment:
      - DOCKER_HOST=tcp://docker:2375
    volumes:
      - ./config:/etc/gitlab-runner
    networks:
      - gitlab-runner
    depends_on:
      - docker

networks:
  gitlab-runner:


volumes:
  docker_lib:
  cache:
  builds:
